name: Himawari-9 Processing

permissions:
  contents: write

on:
  workflow_dispatch:

jobs:
  process_nc:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Himawari Processing
        run: python himawari_process.py
      - name: Run CWA Radar Processing
        run: python radar_process.py
      - name: Run CWA Temp Processing
        run: python real_temp.py
      - name: Run CWA Rain Processing
        run: python Real-time_rainfall.py

      # push
      - name: Commit & Push outputs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git remote set-url origin \
          https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git

          git add outputs/

          git commit -m "Update satellite and radar images [skip ci]" || echo "No changes"

          git push origin HEAD:main
